name: Compile and Upload Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Compile
        run: go build -o output/binary_name ./path_to_main_package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-files
          path: output/
